# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SurpriseAssist' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SurpriseAssist
  react_native_path = "../node_modules/react-native"
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod 'React', path: react_native_path, :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  target 'SurpriseAssistTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SurpriseAssist-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SurpriseAssist-tvOS

  target 'SurpriseAssist-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
